STUBS_TARGET_DIR=$1
PROTOS_ROOT_DIR=$2
PROTO_SRC_DIR=$3

PROTO_GEN_NG=/input-volume/node_modules/.bin/protoc-gen-ng

#Find .protos in directory and count the occurances
echo "Checking $PROTOS_ROOT_DIR for .proto files"
PROTO_FILES_CNT=$(tree $PROTOS_ROOT_DIR | fgrep .proto | wc -l)
if [[ $PROTO_FILES_CNT -lt 1 ]]; then
    echo "ERROR: No proto files were found in the '$PROTOS_ROOT_DIR' directory, but are required to build a library from - exitting"
    exit 1
fi
echo "Found $PROTO_FILES_CNT .proto files in directory: $PROTOS_ROOT_DIR"
echo "Source verified."

# -------------- Generate the proto client library stubs
echo "Starting .proto to grpc client stubs compilation ..."
ALL_PROTO_FILES=$(find $PROTOS_ROOT_DIR -iname "*.proto")
echo "Consuming .proto files: $ALL_PROTO_FILES: "
ALL_PROTOS_DIRS=$(find $PROTOS_ROOT_DIR -iname "*.proto" -exec bash -c  'echo "-I "$(dirname {})' _  {} \;  )
mkdir -p $STUBS_TARGET_DIR

protoc \
--plugin=protoc-gen-ng=$PROTO_GEN_NG \
--include_source_info \
--descriptor_set_out=./description.proto \
--ng_out=$STUBS_TARGET_DIR \
$ALL_PROTOS_DIRS $PROTOS_ROOT_DIR/$PROTO_SRC_DIR/$PROTO_SRC_DIR.proto 



echo ".proto compilation finished."

STUB_FILES_CNT=$(tree $STUBS_TARGET_DIR | grep 'pb.*\.ts' | wc -l)
echo "files generated by proto compilation: $STUB_FILES_CNT"
